sudo: true
language: generic
services:
  - docker
before_install:
  - 'DOCKER_RUN () { docker run --rm --volume "$CURRENT_DIR:/mnt/" --name dev dongsoolee/ubuntu-development
  /bin/bash -c "cd /mnt;$1"; }'
script:
  - DOCKER_RUN "emacs -Q --batch -l ert -l org-multilingual-test.el -f ert-run-tests-batch-and-exit"
env:
  matrix:
  - CURRENT_DIR=`pwd`
notifications:
  slack:
    secure: hmjCAGavGBsNRlm59+6JifTprSh7LcD1/iTmyN0KJhTtHSrKOLVqObicHQHRdd10jH9emCNQ4jDmYizGp4NIxa8vqpJSdffM8ctpcRbFJ2xU+2LWtcM1lNgA0dl2bLDza1UlZgziAkSsSsLhl3FwlNpd6RC3BVdxjr9AvyAxTgkmQMO9oYTKL8Jmn3vDC2IJp89FjpSV+zBdkocyJXFYahKAt1hjXVEieyT0ciYu0boOPtxmQi5KGxIoz/tsghVSQXBwhh7Lmulx0lQdvSqeULKWi1TepIJGtR0dh7RPtXXLXJbJqOr78F+b7bjSzeFo5SjXw0pwomQ3mzdBjm4SCweXxqywdB0zFaFSz6AS4oeOz+P7IENnrs7RGkyh4f2PgeFe1mdBqYRbaa5mJKhXCvwR8sIoyP6ImDxYAyFblqt8WLWzQ25/idr07Qs/ZR1QTFmn2ZnkpJP3Y9M8mExwShulnW/Fvp/d64AgFvTCQs6Y6q/gHwZJizopPV9JXBmNp2Kk4a6NarQ/ZFj0loI4qDRDs0MqCfY5M08YgD6BnAh6dM5adxzz2MqmySkm6yC81bcQOT36n932aDZfjNVV/1+DdWb5l64rU8Yzi5RElMj1GNhgcUEx+vMqh9Nz/SJCvX3TcgMh+h2pzySIogRuzLbZm2p40EzO0LKjX3xR/7s=
